[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dotman"
version = "0.0.2"
dependencies = ['importlib-metadata; python_version < "3.11"']

[project.scripts]
dotman = "dotman:main"
